# Generated by Django 4.2.4 on 2023-08-28 16:41

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('posts', '0002_post_who_liked_alter_post_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='who_disliked',
            field=models.ManyToManyField(related_name='who_disliked', to=settings.AUTH_USER_MODEL),
        ),
    ]
